export const projects = [
    {
        id: 1,
        title: "EscapeTime",
        slug: "escapetime",
        paragraph: "Timer réalisé pour un Escape Game",
        img: "timer.jpg",
        bgColorLeft: "#2b3231",
        bgColorRight: "#f1f1f1",
        bgColor: "#2b3231",
        class: "w-full h-full object-cover",
    },
    {
        id: 2,
        title: "PlaySkroma",
        slug: "playskroma",
        paragraph: "Projet d'un site repertoriant plusieurs jeux de société",
        img: "jeux-plateau.jpg",
        bgColorLeft: "#f1f1f1",
        bgColorRight: "#563f31",
        bgColor: "#563f31",
        class: "w-full h-full object-cover",
    },
    {
        id: 3,
        title: "O'Gaming",
        slug: "o-gaming",
        paragraph:
            "App de rapport de bugs pour aider les développeurs de jeux vidéos",
        img: "OGaming.webp",
        bgColorLeft: "#620c03",
        bgColorRight: "#f1f1f1",
        bgColor: "#620c03",
        class: "w-full h-full object-contain mx-10 mb-52",
    },
    {
        id: 4,
        title: "Angel's Game",
        slug: "angels-game",
        paragraph: "Réalisation d'un site web pour un Escape Game",
        img: "illustration-escape-game.jpg",
        bgColorLeft: "#f1f1f1",
        bgColorRight: "#093b51",
        bgColor: "#093b51",
        class: "w-[400px] h-auto absolute top-32 left-14 rounded shadow",
    },
    {
        id: 5,
        title: "EnglishLearning",
        slug: "english-learning",
        paragraph: "App pour apprendre l'anglais sous forme de card",
        img: "english.jpg",
        bgColorLeft: "#965151",
        bgColorRight: "#f1f1f1",
        bgColor: "#965151",
        class: "w-3/5 rounded absolute top-24 right-10 shadow",
    },
    {
        id: 6,
        title: "ScaP",
        slug: "scap",
        paragraph:
            "Réalisation d'une application mobile de scan de produits de supermarché",
        img: "phone-scap.png",
        bgColorLeft: "#f1f1f1",
        bgColorRight: "#3c6620",
        bgColor: "#3c6620",
        class: "w-[300px] h-auto absolute top-20 left-5 mx-16",
    },
    {
        id: 7,
        title: "DevCraftHub",
        slug: "devcrafthub",
        paragraph: "Projet de création d'un éditeur de texte en ligne",
        img: "IDE.jpg",
        bgColorLeft: "#08121a",
        bgColorRight: "#f1f1f1",
        bgColor: "#08121a",
        class: "w-full h-full object-cover",
    },
];
